### ISSUE TITLE
generate dicovery doesn't work

### ISSUE THREAD

**Issue by Kleak** [dart-lang/rpc#111]
I trying to generate the discovery file so here is the command i launch :

`pub run rpc:generate discovery -a /api -p 8080 -i lib/src/backend/apis/auth.dart`

but the result is 
`Please run 'pub get' in your API package before running the generator.`

Problem i have already do `pub get`

**Comment by sclee15** [comment]
I have the same issue.

**Comment by jakobr-google** [comment]
Looks like a dup of issue #101.
