### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by NTMS2017** [dart-lang/rpc#122]
I am using Dart 2 and creating a Flutter Mobile App. I need a documentation, video, info how to set my own rest api using rpc. Showing me the starting point will be great.

I have Flutter Mobile App that will connect to "Dart RPC Rest API". Then "Dart RPC Rest API" will use dart.io to connect local network socket services. I am not be able to connect from Flutter Mobile App to local network socket services. So, choosing a "Dart RPC Rest API" as middleware it might be good choice for my project. Problem is I don't know how to create a basic Rest Api using RPC package.

Any help please?

**Comment by mkustermann** [comment]
Our [README.md](https://github.com/dart-lang/rpc/blob/master/README.md) should contain detailed instructions on how to use `package:rpc`.

Your flutter app has all of `dart:io` available, so you can connect to any endpoint. If you have trouble using `dart:io` to connect to your local machine during development, you might need find `adb reverse` helpful.
