### ISSUE TITLE
Command in docs doesn't work on a mac

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/rpc#25]
URL='https://your_app_server/api/myApi/v1/rest' mkdir input curl -o input/myapi.json $URL

on a mac causes 4 directories to be made, '-o', 'curl', '-o' and 'input/myapi.json'

Not quite the intended behaviour I suspect.

**Comment by wibling** [comment]
Luke, if you have time please check if this has been fixed with Martin's change!
