### ISSUE TITLE
RPC's goal

### ISSUE THREAD

**Issue by cgarciae** [dart-lang/rpc#28]
Hi,

I've had a look at RPC and I like it very much. I am a Redstone user, and when I look at it I feel at home. 

But first of, why didn't you fork Redstone? The style is incredibly similar, has a bunch of features already, decent documentation, also based on `shelf`, etc.

Second, what specific benefits do you get from RPC? I don't understand very well what is Google Discovery.

Thanks!

**Comment by FaisalAbid** [comment]
AFAIK, Google Discovery lets you easily generate stubs for client apis.

**Comment by cgarciae** [comment]
Ok, a saw a long video about Google Discovery but two questions remain (a guy in the audience asked one but the presenter failed to respond):

1. Does it only work for the Google APIs? (Hope not)
2. When you say things like "generate stubs for client apis", does that mean it auto generates a class for you to use in the client, which contains methods for you to call each services?

I mean, it it something like this: you have an api defined like this
```dart
@(...)
class Service
{
    @(...)
    Future<User> GetUser (...) { ... }
}
```
so when you "compile" you get auto generated classes for you client which would look something like this:
```dart
//Auto-generated class
class ClientService
{
    Future<User> GetUser (...) { ... }
}
```

Am I dreaming too much?

**Comment by wibling** [comment]
No, you are not dreaming too much :) This is exactly how it works.
The rpc package uses the same format (Discovery Document in JSON) as the Google APIs to describe the API you implement via the annotations.
The discovery API generator can then be used to generate a client stub class in Dart as you describe above which is used on the client side to call the server.

**Comment by hangstrap** [comment]
To carry on with the dream. Will the magic that generate the ClientService also provides the logic that performs the http call to the server?

**Comment by andreasolund** [comment]
@hangstrap Yes! To generate a client library you first have to fetch the discovery document from your server and then you run the discoveryapis_generator. The generated library contains the data models and methods to communicate with the RPC server. :)

**Comment by wibling** [comment]
That's correct!
Stubs will always be generated. Either as @andreasolund writes by downloading the Discovery Document from a server and generating stubs and messages from it using the discoveryapis_generator or when putting the client and server code in the same package the stubs can be generated using the rpc:generate command as described in the server codelab (https://www.dartlang.org/codelabs/server/).

**Comment by hangstrap** [comment]
The whole idea sounds great. A simple way of manage and documenting a web
service API.

Is it possible to use the same Discovery Document technology on a Java web
server? If so, could you please supply me with some links

I asked the same question on stackoverflow but am not sure if I was tagging
my question with the correct group.
http://stackoverflow.com/questions/30727030/using-document-discovery-service-on-a-non-app-engine-service
