### ISSUE TITLE
ApiMethod with async

### ISSUE THREAD

**Issue by mmaquevice** [dart-lang/rpc#29]
Congrats for RPC ! :)

Are you planning to support async api method ? 

e.g. : 
```dart
@ApiMethod(path: 'myPath')
MyResponse get(String id) async {
...
}
```

**Comment by cgarciae** [comment]
@mmaquevice your `MyRespose` is a `Future<SomeClass>` since its an async function. RPC already support returning futures. In Dart you can't distinguish a **sync** function that returns a `Future<A>`, from an **async** function that "returns" an `A`

**Comment by mmaquevice** [comment]
My bad, I thought it didn't work but you're right!

**Comment by jkriesel** [comment]
The problem with this is that you can't use the await keyword.  I have an api method that does a request to a separate back-end server (i.e. elastic search) and would like to wait for the response before returning.  Is there a work around for this?

**Comment by Kleak** [comment]
you can use await just add async on the function declaration
```dart
class TestResponse {
  int result;
}

@ApiMethod(name: 'test upload', path: 'test', method: 'GET')
Future<TestResponse> test() async {
  int number = await new Future.value(12);
  return new TestResponse()..result = number;
}
```

**Comment by jkriesel** [comment]
How does this work from the client?  You can't really have a Future of a Future.. can you?

**Comment by Kleak** [comment]
on the client side there is no difference.

**Comment by jkriesel** [comment]
Within the client api, the client api returns a future already.  You'd end up with Future<Future<TestResponse>>.

**Comment by Kleak** [comment]
No just a future
