### ISSUE TITLE
modify rpc code generator to avoid mirrors

### ISSUE THREAD

**Issue by skybrian** [dart-lang/rpc#38]
The http library depends on mirrors and it appears this won't be fixed soon [1].

Therefore, it seems like there should be a way to generate a client-side API that is browser-only and uses the dart:html library directly to make http requests? Then web apps can use the rpc package without using mirrors.

[1] https://github.com/dart-lang/http/issues/1

**Comment by devoncarew** [comment]
+1, we would use this option for dartpad. We see this in our build:
```
  ****************************************************************
  * WARNING: dart:mirrors support in dart2js is experimental,
  *          and not recommended.
  *          This implementation of mirrors is incomplete,
  *          and often greatly increases the size of the generated
  *          JavaScript code.
  *
  * Your app imports dart:mirrors via:
  *   main.dart => package:dart_pad => package:_discoveryapis_commons => package:http => dart:mirrors
```
and it definitely makes me uncomfortable.

**Comment by nex3** [comment]
There's no reason to feel nervous here. The warning is a false positive; the `http` package works just fine in browsers and doesn't cause bloat. We should get rid of the warning, not the package.

**Comment by skybrian** [comment]
Created a bug for fixing dart2js:
https://code.google.com/p/dart/issues/detail?id=23293
