### ISSUE TITLE
Allow access to cookies in a request handler

### ISSUE THREAD

**Issue by polux** [dart-lang/rpc#39]
I see that 392e8eca2256467a704be7255dd2d2f5c7614c2f gives access to the URL and headers of the original HTTP request. Would be nice if it also gave access to cookies.

**Comment by wibling** [comment]
Should be fixed as of commit 659ccabd6b6e91e06bf27f4f99f192fdd19b356a.

**Comment by polux** [comment]
Woot, thanks!
