### ISSUE TITLE
Generate error when using API class in a library

### ISSUE THREAD

**Issue by sanmadjack** [dart-lang/rpc#40]
When using rpc/bin/generate.dart to generate a discovery file or client files, I get this error if my API class is part of a library:

   C:\Users\sanmadjack\Desktop\dart_dev\dartalog>pub run rpc:generate discovery -i lib\server\api\src\dartalog_api.dart -p 8080 -a api
   in ShutdownIsolate: Unhandled exception:
   Uncaught Error: IsolateSpawnException: 'file:///C:/Users/sanmadjack/Desktop/dart_dev/dartalog/lib/server/api/src/dartalog_api.dart': error: line 1 pos 6: url expected
   part of api;
        ^
   Stack Trace:
   #0      Isolate._spawnUri (dart:isolate-patch/isolate_patch.dart:352)
   #1      Isolate.spawnUri (dart:isolate-patch/isolate_patch.dart:308)
   #2      _isolateTrampoline.<_isolateTrampoline_async_body>    (http://localhost:60716/generate.dart:242)
   #3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
   #4      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
   #5      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
   #6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
   #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
   
   #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
   #1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
   #2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
   #3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
   #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

If I change the API class to be separate from a library (so it doesn't have to have the "part of" directive at the top), it generates fine.

**Comment by wibling** [comment]
Hi sanmadjack,

Could you try pointing the -i option at the file with the 'library' statement rather than the one with the 'part of' statement? It should find the @ApiClass in your 'part of' file since it is part of the overall library.

I will work on providing a better error message.

**Comment by wibling** [comment]
I have added the better error message as of commit 659ccabd6b6e91e06bf27f4f99f192fdd19b356a.

**Comment by sanmadjack** [comment]
Thanks, that explains it nicely.
