### ISSUE TITLE
Incompatibility between the shelf and rpc packages.

### ISSUE THREAD

**Issue by brnjamin** [dart-lang/rpc#42]
There seems to be an incompatibility between the shelf and rpc packages.

In rpc [0.4.1] config/api.dart: The handleHttpOptionsRequest expects the 'access-control-request-method' header to be a List:

    Future<HttpApiResponse> handleHttpOptionsRequest(
          ParsedHttpApiRequest request) async {
        var requestedHttpMethods = request.headers['access-control-request-method'];
        List<String> allowed = [];
        assert('OPTIONS'.allMatches(request.methodKey).length == 1);
        if (requestedHttpMethods != null) {
          requestedHttpMethods.forEach((httpMethod) {
            var methodKey =
                request.methodKey.replaceFirst('OPTIONS', httpMethod);
            final List<ApiConfigMethod> methods = _methodMap[methodKey];
            if (methods != null) {
              for (var method in methods) {
                if (method.matches(request)) {
                  allowed.add(httpMethod);
                  break;
               }
              }
            }
          });
        }
When using the shelf [0.5.7] package, the ParsedHttpApiRequest which is passed to this method contains an 'access-control-request-method' header which is a String.

This generates an exception...

When using rpc with dart.io HttpServer, the code works fine and ParsedHttpApiRequest has a List of Strings (with a single element) as value of the 'access-control-request-method' header.

**Comment by wibling** [comment]
Fixed by ebb4d75cc5709d580f075d524aa72b68069a1d76. Will publish new package version soon.

**Comment by wibling** [comment]
New package has been published. If you do a 'pub upgrade' you should pick up version 0.4.2 which should work with the shelf_rpc package and options.
