### ISSUE TITLE
add support for `bool` params

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/rpc#43]
I'm getting this for a new param type:

    CommonServer.compileGet: Query parameter 'useCheckedMode' must be of type int or String.

here's the definition:

    @ApiMethod(method: 'GET', path: 'compile')
    Future<CompileResponse> compileGet({String source, bool useCheckedMode})

I assume bools aren't supported as params, and I'll need to check for a string == 'true' or something? It would be great for them to be supported. Not sure if this is a request for this package or https://github.com/dart-lang/discoveryapis_generator.

**Comment by wibling** [comment]
Fixed by Faisal's commit 2676fdd713e224f5b58416f6eba0ef6dd168768d.
