### ISSUE TITLE
Package rpc 0.5.0 does not match >=0.4.0 <0.5.0

### ISSUE THREAD

**Issue by iamcharliegoddard** [dart-lang/rpc#45]
When resolving dependencies using pub I receive the following message:
```bash
$ pub get
Resolving dependencies... (2.1s) 
Package rpc 0.5.0 does not match >=0.4.0 <0.5.0 derived from:
- shelf_rpc 0.0.3 depends on version >=0.4.0 <0.5.0
```

reviewing the latest commit: https://github.com/dart-lang/rpc/commit/659ccabd6b6e91e06bf27f4f99f192fdd19b356a#diff-fb2d52cd953afedcafc9fe7629c6f132R2

if I revert the change to `pubspec.yaml` `version: 0.5.0` back to `version: 0.4.3` the dependencies resolves:
```bash
$ pub get
Resolving dependencies... (4.0s) 
+ _discoveryapis_commons 0.1.1
+ analyzer 0.25.0+1 (0.25.1-alpha.0 available)
+ args 0.12.2+6 (0.13.1 available)
+ collection 1.1.1
+ crypto 0.9.0
+ discoveryapis_generator 0.7.1+1
+ gcloud 0.2.0+1
+ googleapis 0.8.0 (0.10.0 available)
+ googleapis_beta 0.12.0 (0.14.0 available)
+ http 0.11.2
+ http_parser 0.0.2+6
+ intl 0.12.4
+ logging 0.9.3 (0.11.1 available)
+ logging_handlers 0.8.0
+ matcher 0.11.4+4 (0.12.0+1 available)
+ mock 0.11.0+4 (0.12.0 available)
+ mockito 0.8.2 (0.10.1 available)
+ path 1.3.5
+ petitparser 1.4.3
+ quiver 0.20.0 (0.21.4 available)
+ shelf 0.5.7 (0.6.1+2 available)
+ shelf_path 0.1.2
+ shelf_route 0.11.0+1 (0.12.0 available)
+ shelf_rpc 0.0.3
+ source_span 1.1.2
+ stack_trace 1.3.2
+ string_scanner 0.1.3+1
+ unittest 0.11.6+1 (0.12.2 available)
+ uri 0.9.5 (0.10.0 available)
+ utf 0.9.0+2
+ watcher 0.9.5
+ yaml 2.1.2
Changed 32 dependencies!
Precompiling dependencies... 
Loading source assets... 
Precompiled gcloud and intl.
Precompiling executables... 
Loading source assets... 
Precompiled discoveryapis_generator:generate.
```
I believe the `shelf_rpc` project needs to have their rpc dependency incremented to rpc 0.5.0 (https://github.com/dart-lang/shelf_rpc/blob/master/pubspec.yaml#L12). I'll be adding an issue to that project but feel there should be a coordinating issues here.

thoughts?

**Comment by devoncarew** [comment]
It would be great to avoid the circular dependency from `rpc` <==> `shelf_rpc`. `shelf_rpc` is only used by the `example/` directory; perhaps it's constraint could be broadened here to `any`?

@wibling

**Comment by wibling** [comment]
If I update the shelf_rpc dependency to any I get version 0.0.1 of shelf_rpc which also seems broken (ie. the example will not work).
AFAICT the issue here is that I didn't update the shelf_rpc dependency to the latest rpc package. I will update that instead.
How would the 'any' dependency help us except hide the fact that the shelf_rpc package should be updated to use the latest version?
