### ISSUE TITLE
Add a Future method to toyapi.dart example

### ISSUE THREAD

**Issue by daftspaniel** [dart-lang/rpc#48]
Add a Future method to toyapi.dart example.

This is mentioned in the readme and it would be great to have a working example for those new to it. Or will this become Async? :-)

**Comment by FaisalAbid** [comment]
I'll add an example to it and send a PR

**Comment by FaisalAbid** [comment]
Hi Dafts, this example is now in the repo. Let me know if this issue is good to close.

**Comment by anettan** [comment]
thante.-now in the repo.

**Comment by daftspaniel** [comment]
@FaisalAbid That's just the ticket - please close the issue! Thanks for adding this :+1:

**Comment by FaisalAbid** [comment]
@wibling - good to close

**Comment by wibling** [comment]
Sure!
