### ISSUE TITLE
Error when running rpc generate client

### ISSUE THREAD

**Issue by hangstrap** [dart-lang/rpc#53]
http://stackoverflow.com/questions/30934334/dart-error-running-rpc-generate-client?noredirect=1#comment49905572_30934334

I am trying to follow the "Beware the Nest o’ Pirates" tutorial https://www.dartlang.org/codelabs/server/ and have hit a problem when I try to generate the client code for the PiratesApi

When I run the command

pub global run rpc:generate client -i lib/server/piratesapi.dart -o lib/client
I get the following error message

Failed executing command 'discoveryWithImports' with error:
No constructor 'ApiParser' with matching arguments declared in class 'ApiParser'.
NoSuchMethodError: incorrect number of arguments passed to method named 'ApiParser'
Receiver: Type: class 'ApiParser'
Tried calling: ApiParser(strict: true)
Found: ApiParser()

I am running Ubuntu 14.04
Dart STK 1.10.1

My pubspec.lock is 

packages:
  _discoveryapis_commons:
    description: _discoveryapis_commons
    source: hosted
    version: "0.1.1"
  analyzer:
    description: analyzer
    source: hosted
    version: "0.24.1"
  args:
    description: args
    source: hosted
    version: "0.12.2+6"
  browser:
    description: browser
    source: hosted
    version: "0.10.0+2"
  collection:
    description: collection
    source: hosted
    version: "1.1.0"
  crypto:
    description: crypto
    source: hosted
    version: "0.9.0"
  discoveryapis_generator:
    description: discoveryapis_generator
    source: hosted
    version: "0.7.1+1"
  gcloud:
    description: gcloud
    source: hosted
    version: "0.2.0+1"
  googleapis:
    description: googleapis
    source: hosted
    version: "0.8.0"
  googleapis_beta:
    description: googleapis_beta
    source: hosted
    version: "0.12.0"
  http:
    description: http
    source: hosted
    version: "0.11.2"
  http_parser:
    description: http_parser
    source: hosted
    version: "0.0.2+6"
  intl:
    description: intl
    source: hosted
    version: "0.12.2"
  logging:
    description: logging
    source: hosted
    version: "0.9.3"
  logging_handlers:
    description: logging_handlers
    source: hosted
    version: "0.8.0"
  matcher:
    description: matcher
    source: hosted
    version: "0.11.4+4"
  path:
    description: path
    source: hosted
    version: "1.3.4"
  petitparser:
    description: petitparser
    source: hosted
    version: "1.3.7"
  quiver:
    description: quiver
    source: hosted
    version: "0.20.0"
  rpc:
    description: rpc
    source: hosted
    version: "0.4.1"
  source_span:
    description: source_span
    source: hosted
    version: "1.1.2"
  stack_trace:
    description: stack_trace
    source: hosted
    version: "1.2.4"
  string_scanner:
    description: string_scanner
    source: hosted
    version: "0.1.3+1"
  uri:
    description: uri
    source: hosted
    version: "0.9.5"
  utf:
    description: utf
    source: hosted
    version: "0.9.0+2"
  watcher:
    description: watcher
    source: hosted
    version: "0.9.5"
  yaml:
    description: yaml
    source: hosted
    version: "2.1.2"

**Comment by goranj** [comment]
I made this work by activating the rpc package with a version constraint:
```
pub global activate rpc 0.4.1
```
https://www.dartlang.org/tools/pub/cmd/pub-global.html

**Comment by wibling** [comment]
As goranj mentions it is due to the different rpc version. When you run pub global activate it gets the latest version into your .pub-cache. However the codelab expects 0.4.x. You can work around this by constraining the activate as above.

That said I have just updated the codelab to use rpc 0.5.0 so it should work without constraints again.
See https://github.com/dart-lang/one-hour-codelab/commit/4ea72b53ac38adc87d22cd6bfc5566d9d1fa2bb8 for details.
