### ISSUE TITLE
how to redirect  url

### ISSUE THREAD

**Issue by thelordofthetimes** [dart-lang/rpc#54]
in api method, how to redirect url same as 
``` dart
redirect(url);
```

**Comment by thelordofthetimes** [comment]
anybody here  to develop ?

**Comment by FaisalAbid** [comment]
Hi! Apologize for the late response. I don't think there is a way to currently do this inside the API method.

@wibling am I correct? I think we should expose the HttpRequest object for api methods to use if they want, what do you think?

**Comment by thelordofthetimes** [comment]
I found solution after read change log, code..., many time. Must be use context same as below code

```dart
    context.responseStatusCode = HttpStatus.FOUND;
    context.responseHeaders[HttpHeaders.LOCATION] = <url to redirect>
```

**Comment by FaisalAbid** [comment]
oh awesome, I think we should document this more.

Thanks for looking into it

**Comment by thelordofthetimes** [comment]
Hey FaisalAbig, this project has also been developed ?

**Comment by FaisalAbid** [comment]
I've very recently started to contribute to the project. The project is developed by @wibling

**Comment by thelordofthetimes** [comment]
I'm try to make api for media at [cdna.media](https://github.com/thelordofthetimes/cdna.media).
So I hope dartlang and them library is still developing. I was a bit worried because last commit from a few months ago. What do you think about that ?

**Comment by FaisalAbid** [comment]
Don't worry, my entire startup relies on this API also, one of the reasons why I'm trying to get more active here is so the api does not get left behind, I'll make sure to keep it active and maintained

**Comment by thelordofthetimes** [comment]
So good. Documentation is required for this project. It is difficult for a new develper looking api. Can I do  this ?

**Comment by FaisalAbid** [comment]
The Readme.md file contains a good example of how it works, check out toyapi.dart also. There is no formal documentation yet, but that is something that is on the radar to do, a wiki of sorts

**Comment by thelordofthetimes** [comment]
Okey, that's good in this time. But in future is still require documentation, may be. I'm close this issuse and come back with new issuse later. Have a nice day !

**Comment by FaisalAbid** [comment]
Thanks!
