### ISSUE TITLE
RPC is using a very old dependencies

### ISSUE THREAD

**Issue by hangstrap** [dart-lang/rpc#55]
Could you possibly update them?

http://stackoverflow.com/questions/31156495/dart-pub-get-fault/31157111#31157111

thanks

**Comment by FaisalAbid** [comment]
I'll take a look, thanks

**Comment by wibling** [comment]
This should be fixed as of change: 730531bd932709479f8fdffb2f7b5cc9fb0a4517

Please let us know if this is still an issue.
