### ISSUE TITLE
Complex dart-lang/gcloud data structures 

### ISSUE THREAD

**Issue by tonyclickspace** [dart-lang/rpc#58]
Tried to make a single class that could be understood by both gcloud and rpc packages. As soon as it got complex, i.e. beyond primitives, gcloud package conflicts with rpc, throwing this error:
```
RPC: Failed to parse API.

/instagram/v1:
Key: type: Unsupported property type: Type

#0      ApiServer.addApi (package:rpc/src/server.dart:71:7)
#1      main (file:///app/bin/server.dart:29:14)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

The why: Using gcloud, items that go in and out of the database are required to extend Model. All of the database-storable values have to be either primitives, or other models. To link to other models, you need to provide a database Key.  Here's an example of an integer, string and Key:

```
@IntProperty() int someInt;
@StringProperty() String someString;
@ModelKeyProperty() Key someKey;
```

The Key class has a variable of type 'Type' - which is unsupported in rpc, so it fails out.

gcloud can't store a Map, so I'm stuck with this Model structure. Solutions aren't ideal either, as the Key var is just a reference to the actual data. rpc may eventually need methods by which we can omit / add fields to the parser.

Unless I'm missing something, and this is already available... I don't mind looking like an idiot if that's true though!

**Comment by wibling** [comment]
Good point. We have discussed this before. I have send out a change adding support for ignored fields in a request/response schema class. See https://codereview.chromium.org/1276843005/.

**Comment by wibling** [comment]
Should be supported now.
