### ISSUE TITLE
Send error "codes" to clients

### ISSUE THREAD

**Issue by enyo** [dart-lang/rpc#63]
There is an `RpcError` that allows me to send a specific error code with a message. The `RpcError` also has a `.name` attribute that is never used (as far as I can see).

It would be great if there was an attribute (for example the `name`) that I can use to send specific error codes to the clients.

Right now it gets submitted as

```json
{
  "error": {
    "code": 404,
    "message": "<error message>"
  }
}
```

Why not add the `name` in there as well?

**Comment by wibling** [comment]
Good idea. I will look into this shortly. I am currently balancing my time between a few other projects so I am a little slow with addressing RPC issues. You are very welcome to submit changes yourself and I will try to be quick about reviewing and merging them. Otherwise I will try to set aside some time ASAP for RPC.

**Comment by enyo** [comment]
Hey, I can gladly help out. Just want to make sure I'm not doing something unwanted in the lib.
I have looked at the [Google JSON style guide](http://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml?showone=error#error), and they also don't use any error codes in their responses. What they _do_ have though, is a [list of errors](http://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml?showone=error#Reserved_Property_Names_in_the_error_object). So we could follow that guideline, and extend RPC to support a list of errors. They have a `reason` that can be used as an error code.
What do you think @wibling ?

**Comment by sgjesse** [comment]
That looks like the right thing to do. This is what the Google REST APIs
are following, e.g.
https://cloud.google.com/storage/docs/json_api/v1/status-codes.

**Comment by enyo** [comment]
This raises another point though: should the RPC library try to follow the Google JSON style guide completely? If so, there is a lack of a "default" message or mechanism that helps in following the spec. Right now it's mostly "just return the object you want" and you need to take care of following the style guide yourself.

**Comment by enyo** [comment]
And either I don't quite get the style guide, or it seems that the storage API doesn't follow it neither. The guide suggests, that all content goes into into `data` like:

```json
{
  "data": {
    "name": "All content here"
  }
}
```

And if both, `data` and `error ` exist, then `data` should be ignored. For a list of items it should be:

```json
{
  "data": {
    "items": []
  }
}
```

Soo... I don't know how seriously this style guide should be taken?

**Comment by sgjesse** [comment]
Looking at the sample from the style guide:

{
  "apiVersion": "2.0",
  "error": {
    "code": 404,
    "message": "File Not Found",
    "errors": [{
      "domain": "Calendar",
      "reason": "ResourceNotFoundException",
      "message": "File Not Found
    }]
  }
}

and the sample from the storage API:

{
"error": {
 "errors": [
  {
   "domain": "global",
   "reason": "required",
   "message": "Login Required",
   "locationType": "header",
   "location": "Authorization"
  }
 ],
 "code": 401,
 "message": "Login Required"
 }
}

They seems to follow the same scheme. As far as I can see storage use error
and not data.

---
Søren Gjesse
Software Engineer, Google Denmark
CVR nr. 28 86 69 84

**Comment by wibling** [comment]
@enyo we should try to follow the style guide as much as possible, but I think having more information in e.g. an error is okay. The client can always ignore fields it doesn't know.

Using the error field sounds like a good idea to me.

**Comment by enyo** [comment]
I was talking about success messages. The style guide says that you either have
```json
{"error": {}}
```
or
```json
{"data":{}}
```
depending on whether the request had an error or was successful.
In case of an error the spec is followed properly, but in case of a successful request it is not.

So in case of errors it's clear how to do it IMO: use the `error` field, with and additional `errors` subfield for more information. That follows the spec, and is how RPC already does it (apart for the missing `errors` list).

I just wanted to point out that it would be great to also follow the spec in case of success, and provide the developers using this library with an easy mechanism to reply with messages following the style guide.

**Comment by enyo** [comment]
Apart from the `data` fields in data messages, do you both agree on using `{"error": { "errors": []}}` to send additional error information, like error codes @wibling & @sgjesse? If so I can create a PR.
