### ISSUE TITLE
Decode URL query & path

### ISSUE THREAD

**Issue by enyo** [dart-lang/rpc#64]
When using the generated client libraries for RPC, the path and query components are encoded automatically (eg: `%20`). They are not, however decoded on the server side, so I need to decode them in the `ApiMethod` manually.

I think that this should be done behind the scenes.

**Comment by wibling** [comment]
I will look into this ASAP.

**Comment by sanmadjack** [comment]
This issue is still occuring, and the pull request still hasn't been merged. Will this be resolved soon, or should I start wrapping everything in url decodes?
