### ISSUE TITLE
Get the connectionInfo of a request

### ISSUE THREAD

**Issue by fschuetz04** [dart-lang/rpc#72]
The `HttpRequest` object has the property `connectionInfo` with data like the remote IP adress, but I can't find a way to get this info in an RPC method - being not accessible via `context`.

Do you think this could be changed?

**Comment by enyo** [comment]
I have the same question / request. Is there a way of getting client information in an RPC method?

**Comment by fschuetz04** [comment]
I searched through the code and found out that only a little change is necessary, but my solution is very dirty. Maybe I'll create a pull request.

**Comment by enyo** [comment]
In the end I created a zone in which every http request is running, and am storing the initial HttpRequest in a zone variable. This works well.
