### ISSUE TITLE
Enormous memory footprint, when client has a lot of pending requests.

### ISSUE THREAD

**Issue by deftomat** [dart-lang/rpc#77]
We have an application, which in some circumstances store messages in queue (paused stream) and send them all later. For example, when target is down and our application waiting for new connection.

However, if a lot of messages are sended by [sendRequest()](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/client.dart#L94) at the same time, than the memory footprint of application is enormous due to stored stackTraces in [_pendingRequests](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/client.dart#L32).

Maybe, there could be an optional parameter in [sendRequest()](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/client.dart#L94), which prevent to build a Chain instance.

**Comment by mkustermann** [comment]
Hi @deftomat. The links methods you are referring to belong to [package:json_rpc_2](https://github.com/dart-lang/json_rpc_2). Is this maybe the wrong issue tracker?

cc @nex3

**Comment by deftomat** [comment]
Ooo, you're right. My bad. I'm sorry...
