### ISSUE TITLE
Using an @ character in a path parameter breaks the method

### ISSUE THREAD

**Issue by enyo** [dart-lang/rpc#81]
If I'm not mistaken, a `@` character is a valid character inside a URL path segment. That's also the reason, why it is _not_ encoded when invoking the method.

But when the request is made, the server returns: [`No method found matching HTTP method: [...]`](https://github.com/dart-lang/rpc/blob/master/lib/src/config/api.dart#L45)

This happens, because the [`method.matches`](https://github.com/dart-lang/rpc/blob/master/lib/src/config/method.dart#L38) call, [uses a parser](https://github.com/dart-lang/rpc/blob/master/lib/src/parser.dart#L250) that does *not* include the `@` sign.

**Comment by PaulWoitaschek** [comment]
Same for `=`. Any news on this?

**Comment by enyo** [comment]
@mkustermann just pointed out that:

1. The paths defined by `ApiMethod` follow the [URI Template spec](https://tools.ietf.org/html/rfc6570)
2. [Section  3.2.2](https://tools.ietf.org/html/rfc6570#section-3.2.2) defines that each character in a variable must be in the unreserved character set
3. And the [unreserved characters](https://tools.ietf.org/html/rfc6570#section-1.5) are `ALPHA / DIGIT / "-" / "." / "_" / "~"`

So it is correct, not to allow `@` or `=` in the path. We will switch to a `GET` variable.
