### ISSUE TITLE
Code generation no longer working with package imports in Dart 1.14

### ISSUE THREAD

**Issue by mastodon0** [dart-lang/rpc#84]
After upgrading to Dart 1.14 I tried to generate my client-code like I always did before:
```pub global run rpc:generate client -i lib/server/piratesapi.dart -o lib/client```
and got this error:
```Load Error for "package:shelf_auth/shelf_auth.dart": No mapping for 'shelf_auth' package when resolving 'package:shelf_auth/shelf_auth.dart'.```

shelf_auth is a package that is imported in my api file to handle authentication. 
I tracked the problem down to the new way the package references are handled (Package Configuration File). 
It seems that only the configuration file of the rpc package in ~/.pub-cache/global_packages/rpc/.packages gets searched for unknown packages and not the the configuration file of the project itself. After I manipulated ~/.pub-cache/global_packages/rpc/.packages to include a definition for shelf_auth, I got the generator to work again.

Is there any other way to import packages? Is the rpc:generate client command still supported since it isn't mentioned in the readme anymore?

**Comment by zoechi** [comment]
I don't use the rpc package myself, therefore just a guess.  
If you need to add it to your project as dependency/dev_dependency you could try to run it without `global` (just `pub run rpc:generate ...).

**Comment by mastodon0** [comment]
Gread idea, thank you!
An additional dev_dependency wasn't even needed because the project wouldn't work without the rpc dependency.
