### ISSUE TITLE
rpc deps are pinned to old versions

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/rpc#91]
The deps of rpc are pinned to older versions. `rpc` is in use by several other projects; the older deps mean that they are selecting older package versions when running `pub get` / `pub upgrade`, and tihs increases the risk of version lock when one of the other transitive dependencies requires a version newer then one that rpc supports.

**Comment by Kleak** [comment]
Upgrade version could be cool but also migrate unittest to test an rewrite some test in order to use `pub run test`

**Comment by mkustermann** [comment]
We've migraded from `package:unittest` to `package:test` and widened several constraints.
