### ISSUE TITLE
Fix JSON serialization for response complex objects

### ISSUE THREAD

**Issue by unco-games** [dart-lang/rpc#96]
Hello!

I'm trying to create API-server for my project and use inheritance for different responses. But I discovered that json-serialisation doesn't work for complex objects.

class BaseResponse {
String text  = 'Base text';
  BaseResponse();
}

class SignUpResponse extends BaseResponse {
  SignUpResponse();
}

@ApiMethod(method: 'POST', path: 'sign_up')
  SignUpResponse signUp(SignUpRequest request) {
  return new SignUpResponse();
}`

Last method instead {"text": "Base text"} return to client nothing;

**Comment by seanmccleary** [comment]
I agree that this would be very useful.  There's already an open issue for this (with a branch illustrating the requested behavior) here:

https://github.com/dart-lang/rpc/issues/90

**Comment by mkustermann** [comment]
@seanmccleary has added support for including fields in superclass in serialization/deserialization.

Since this repo issue was about this, I'll go ahead and close this bug.
