### ISSUE TITLE
Upgrade gcloud dependency to 0.3.0

### ISSUE THREAD

**Issue by avoivo** [dart-lang/rpc#97]
Gcloud package recently released 0.3.0 adding support for latest google apis. In a existing project of mine that uses both rpc and gcloud, i changed the gcloud dependency to version 0.3.0 and i got the following error.
```
Package rpc has no versions that match >=0.5.6+1 <0.6.0 derived from:
- pub_test depends on version ^0.5.6+1
```

Are there any suggestions or workarounds?

**Comment by zoechi** [comment]
You can use `dependency_overrides:` to unblock you until an update is published.

**Comment by avoivo** [comment]
Thanx @zoechi

**Comment by mkustermann** [comment]
I've just published a new version which widens several dependency constraints, including the one for `package:gcloud`.
